### ISSUE TITLE
issue running DVM to monitor pulsechain

### ISSUE THREAD

**Issue by Trick03** [tellor-io/disputable-values-monitor#101]
Hi we are having some issue monitoring the pulsechain, below is the message we are getting from the logs

`Could not find contract info for chain_id 941`

but the other chain seems to be working as we can see some data from the dashboard. kindly advice if we miss something upon installing the said service. 

Thanks in advance.

**Comment by oraclown** [comment]
> Hi we are having some issue monitoring the pulsechain, below is the message we are getting from the logs
> 
> `Could not find contract info for chain_id 941`
> 
> but the other chain seems to be working as we can see some data from the dashboard. kindly advice if we miss something upon installing the said service.
> 
> Thanks in advance.

Thanks for reaching out. We'll take a look and get back to you!

What will help us reproduce and debug the problem is if you post the commit hash of the version that you're using, output from the console log, and/or output from running `pip freeze` in the environment that you're working in.

**Comment by tallywiesenberg** [comment]
@Trick03 please also include your `endpoints.yaml` :)

**Comment by tallywiesenberg** [comment]
@Trick03 Thank you!! For context, the DVM reads tellor contract addresses from `telliot-core/src/telliot_core/data/contract_directory.json`. I looked up pulsechain (chain 941) in the version of `telliot-core` you have as a dependency, and I found your redeployment (If I understand correctly, you have redeployed tellor360 to pulsechain) has not been added to the `contract_directory.json`. Can you make a PR in `telliot-core` to add your new deployment addresses? Please let me know if you need any help :))

For reference: https://github.com/tellor-io/telliot-core/blob/v0.2.0/src/telliot_core/data/contract_directory.json

**Comment by oraclown** [comment]
> Hi @tallywiesenberg, is it possible to use the old service tellorflex instead, this also includes the reporter using tellorflex. please advise on the possibilities. Thanks

Hey @Trick03 , have you currently deployed the tellor 360 contract suite? Because what's listed is that you have the tellor flex ones deployed (can verify by searching for 941 on [this page](https://github.com/tellor-io/telliot-core/blob/main/src/telliot_core/data/contract_directory.json)). If you've actually deployed the 360 ones, then there's the bug, and the simple fix will be to move those contract addresses to `tellor360-oracle` and `tellor360-autopay` instead.

If you have the flex ones deployed, then the bug is in the disputable values monitor code, as [it's only watching contracts labeled "tellor360-oracle"](https://github.com/tellor-io/disputable-values-monitor/blob/main/src/tellor_disputables/cli.py#L78). When `get_events` is called, `get_contract_info` is called within, and logs the message you were getting (`Could not find contract info for chain_id`) because there is no `tellor360-oracle` contract address listed for chain id 941. See [here](https://github.com/tellor-io/telliot-core/blob/main/src/telliot_core/data/contract_directory.json#L96).

Let us know, we're happy to help get this fixed and working for you!

cc @tallywiesenberg

**Comment by tallywiesenberg** [comment]
Kudos to @oraclown , and @Trick03 I've reinstated to the DVM monitoring for the tellorflex contracts, including the deployment on pulsechain at 0xB0A15Da1538D0968A32858273E64fcd0F9869283.

**Comment by tallywiesenberg** [comment]
Also, let me know if you'd like assistance deploying the newest version of the tellorflex contract to pulsechain!
